### ISSUE TITLE
你好，加aps的意义合在呢？作者可否解释一下？

### ISSUE THREAD

**Issue by oneCodeSuperman** [lililuya/Wav2Lip288#1]
你好，加aps的意义合在呢？作者可否解释一下？
你好，加aps的意义合在呢？作者可否解释一下？
你好，加aps的意义合在呢？作者可否解释一下？
你好，加aps的意义合在呢？作者可否解释一下？
你好，加aps的意义合在呢？作者可否解释一下？

**Comment by lililuya** [comment]
您好，只是简单参考了一下SIDGAN这篇论文，因为原版本的syncnet非常难训，但是我那个代码是由很大问题的，您还是参考原wav2lip的仓库吧

oneCodeSuperman ***@***.***> 于2024年1月26日周五 17:18写道：
