### ISSUE TITLE
请问你和yyheart是同一个项目吗

### ISSUE THREAD

**Issue by SakuraMaiii** [lililuya/Wav2Lip288#2]
https://github.com/yyheart/Wav2Lip288
我看你们的仓库很像，另外不知您是否有该代码的效果可以看下，期待您的回复

**Comment by lililuya** [comment]
> https://github.com/yyheart/Wav2Lip288 我看你们的仓库很像，另外不知您是否有该代码的效果可以看下，期待您的回复

您好，我这个仓库废弃了，我的仓库代码有些问题，并没有训出结果，您可以参考其他开发者的仓库。
